# HW 3

## Problem 1
Write a NumPy program to subtract the mean of each row of a given matrix.

<font color='green'> Explanation starts here</font>

first trial

```
import numpy as np

x = np.random.rand(5, 10)
y = x - x.mean(axis = 1)
print(y)
```
operands could not be broadcast together with shapes (5,10) (5,)

차원이 맞지 않아 에러 발생

```
keepdims = True
```
옵션 추가
```
print(x.mean(axis = 1).shape)
```
(5,)
```
print(x.mean(axis = 1, keepdims = True).shape)
```
(5, 1)

keepdims = True를 넣으면 2차원으로 유지가 되는 것을 확인할 수 있음

<font color='green'> Explanation ends here</font>


<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
import numpy as np

x = np.random.rand(5, 10)
print("original matrix:")
print(x)
y = x - x.mean(axis = 1, keepdims = True)
print("\n subtract the mean of each column of a given matrix")
print(y)
x.mean(axis = 1, keepdims = True).shape

original matrix:
[[8.32741464e-01 7.42395309e-01 8.23157817e-01 3.59838840e-01
  8.11502633e-02 6.90029109e-01 8.92187835e-01 8.68978722e-01
  1.43941297e-01 5.45705809e-01]
 [4.28703698e-01 8.92054782e-01 8.63692431e-01 7.42137594e-01
  9.99091717e-01 5.83395601e-01 6.09156803e-01 9.60333133e-02
  9.32271921e-01 8.11066768e-01]
 [8.36049269e-01 2.87795962e-01 5.92902966e-01 6.05422318e-01
  3.19938859e-04 2.93696841e-01 7.68412118e-01 2.94508506e-01
  1.30227354e-01 2.77796794e-01]
 [8.77089066e-01 7.21864353e-01 8.20847446e-01 6.43423292e-01
  8.82953981e-01 4.18910167e-01 6.92324086e-01 7.16150177e-01
  6.83577827e-01 7.24811527e-01]
 [9.87742571e-01 6.43671870e-01 2.37169941e-02 2.71675223e-01
  2.96063878e-01 5.31015792e-02 7.53219720e-01 1.41465523e-01
  6.28502588e-01 8.00946274e-01]]

 subtract the mean of each column of a given matrix
[[ 0.23472882  0.14438266  0.22514517 -0.23817381 -0.51686238  0.09201646
   0.29417519  0.27096608 -0.45407135 -0.05230684]
 [-0.26705677  0.19629432  0.16793197  0.04637713  0.30333125 -0.11236486
  -0.08660366 -0.59972715  0.23651146  0.1153063 ]
 [ 0.42733606 -0.12091724  0.18418976  0.19670911 -0.40839327 -0.11501637
   0.35969891 -0.1142047  -0.27848585 -0.13091641]
 [ 0.15889387  0.00366916  0.10265225 -0.0747719   0.16475879 -0.29928503
  -0.02587111 -0.00204501 -0.03461737  0.00661633]
 [ 0.52773195  0.18366125 -0.43629363 -0.1883354  -0.16394674 -0.40690904
   0.2932091  -0.3185451   0.16849197  0.34093565]]

(5, 1)

## Problem 2
Write a NumPy program to subtract the mean of each column of a given
matrix.

<font color='green'> Explanation starts here</font>

1번 문제에서 axis = 0으로 변경

axis = 0으로 각 컬럼의 평균을 구하는 경우 keepdims = True 옵션이 필요하지 않음.


<font color='green'> Explanation ends here</font>


<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
import numpy as np

x = np.random.rand(5, 10)
print("original matrix:")
print(x)
y = x - x.mean(axis = 0)
print("\n subtract the mean of each column of a given matrix")
print(y)

original matrix:
[[0.38444021 0.43302506 0.46806107 0.7525645  0.84820931 0.27749517
  0.18766221 0.07545053 0.78856237 0.18791217]
 [0.91558047 0.64564995 0.04260959 0.41591255 0.20123407 0.09289247
  0.97410824 0.05889848 0.804159   0.11700639]
 [0.95111987 0.06761322 0.18994666 0.46189676 0.64132507 0.21712094
  0.65888448 0.25705909 0.35227683 0.12162469]
 [0.062169   0.6258993  0.67641455 0.66471161 0.84299701 0.26760256
  0.75931562 0.92994746 0.98477804 0.42383208]
 [0.88472196 0.78057325 0.5063801  0.07914945 0.76256144 0.56170425
  0.55881944 0.40562773 0.76048616 0.82343217]]

 subtract the mean of each column of a given matrix
[[-0.25516609 -0.07752709  0.09137868  0.27771753  0.18894393 -0.00586791
  -0.44009579 -0.26994613  0.05050989 -0.14684933]
 [ 0.27597417  0.13509779 -0.33407281 -0.05893443 -0.45803131 -0.19047061
   0.34635024 -0.28649818  0.06610652 -0.21775511]
 [ 0.31151357 -0.44293894 -0.18673574 -0.01295022 -0.01794031 -0.06624214
   0.03112648 -0.08833757 -0.38577565 -0.21313681]
 [-0.5774373   0.11534715  0.29973216  0.18986464  0.18373163 -0.01576052
   0.13155762  0.5845508   0.24672556  0.08907058]
 [ 0.24511566  0.27002109  0.12969771 -0.39569752  0.10329606  0.27834118
  -0.06893856  0.06023107  0.02243368  0.48867067]]

## Problem 3
Write a NumPy function to concatenate two given two dimensional arrays of
shape (n, p) and (n,q), respectively, to create (n, p+q) array.

<font color='green'> Explanation starts here</font>

np.concatenate()를 이용하여 열 방향으로 합쳐지도록 axis = 1을 옵션으로 둔다.

<font color='green'> Explanation ends here</font>


<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
import numpy as np

def concat_column(x1, x2):
    y = np.concatenate((x1, x2), axis = 1)
    print(y)

x1 = np.array([[4.5, 3.5], 
               [5.1, 2.3]])
x2 = np.array([[1],
               [2]])
concat_column(x1, x2)

[[4.5 3.5 1. ]
 [5.1 2.3 2. ]]

## Problem 4
Write a NumPy function to concatenate two given two dimensional arrays of
shape (n, p) and (m,p), respectively, to create (n+m, p) array

<font color='green'> Explanation starts here</font>

problem 3에서 axis = 0으로 옵션을 변경해주면 된다.

<font color='green'> Explanation ends here</font>


<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
import numpy as np

def concat_row(x1, x2):
    y = np.concatenate((x1, x2), axis = 0)
    print(y)

x1 = np.array([[4.5, 3.5], 
               [5.1, 2.3]])
x2 = np.array([[4, 3],
               [5, 2],
               [1, 1]])
concat_row(x1, x2)

[[4.5 3.5]
 [5.1 2.3]
 [4.  3. ]
 [5.  2. ]
 [1.  1. ]]

## Problem 5
[Video Record] Create a python function to create a matrix having a boundary with a value of 1 and an inner one 0 the legend is shown below for given row and column numbers：


```
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
```

[video solution](https://youtu.be/o3esL4y6Klw)

<font color='green'> Explanation starts here</font>

0으로 채워진, m개의 행과 n개의 열을 가진 행렬 x를 만든다.dtype = int 옵션을 설정하여 소수점을 없애준다.

```
x = np.zeros((m,n), dtype = int)
```

이중 for문을 사용하여 행렬 x에서 행의 인덱스가 0 또는 m-1이거나 열의 인덱스가 0 또는 n-1이면 값을 1로 바꾸어 저장한다.즉 boundary에 있으면 1로 바꾸어 준다.

```
 for i in range(m):
        for j in range(n):
            if (i in [0, m-1]) | (j in [0, n-1]):
                x[i][j] = 1
```

<font color='green'> Explanation ends here</font>


<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
def printBoundary(m, n):
    x = np.zeros((m,n), dtype = int)
    for i in range(m):
        for j in range(n):
            if (i in [0, m-1]) | (j in [0, n-1]):
                x[i][j] = 1
    return x
printBoundary(10,10)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## Problem 6
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th
moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==
```
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
```
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Write a Python function to find moving average in an array over a window with an array and window size as inputs:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window size 3.

<font color='green'> Explanation starts here</font>

x = input list, k = window size

The moving average sequence has n-k+1 values.

따라서 len(x)-k+1 만큼 for문을 돌리고, np.average를 이용하여 k개 원소의 평균을 구하여 각각을 프린트하는 코드 작성
```
for i in range(len(x)-k+1):
    avr = np.average(x[i:i+k])
    print(avr)
```
<font color='green'> Explanation ends here</font>


<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
import numpy as np

def moving_average(x, k):
    for i in range(len(x)-k+1):
        avr = round(np.average(x[i:i+k]))
        print("y", i+1, "=", avr)
        
x = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3
moving_average(x, k)

y 1 = 5
y 2 = 5
y 3 = 6
y 4 = 7
y 5 = 10
y 6 = 29
y 7 = 49
y 8 = 73
y 9 = 84
y 10 = 93
y 11 = 116

## Problem 7
 [Video Record] You are given the following information of drivers:


a> Create an array “N” of shape [3, 5] to represent the number of accidents. Similarly, create arrays of “Salary” and “Sports” of shape [3,5] each to represent the salary and sports car.

[video solution](https://youtu.be/gkoAjudfoRc)

<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
import numpy as np

N = np.array([[0,1,0,1,2],
              [1,3,2,1,0],
              [0,0,0,1,3]])
Salary = np.array([[157,167,130,145,170],
                   [250,260,263,273,290],
                   [301,120,30,100,502]])
Sports = np.array([[1,1,1,1,1],
                   [0,0,0,0,0],
                   [0,0,0,0,0]])

In [ ]:
N

array([[0, 1, 0, 1, 2],
       [1, 3, 2, 1, 0],
       [0, 0, 0, 1, 3]])

In [ ]:
Salary

array([[157, 167, 130, 145, 170],
       [250, 260, 263, 273, 290],
       [301, 120,  30, 100, 502]])

In [ ]:
Sports

array([[1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

b> Create an array “Y” of shape [3,5,3] where (i,j,1)-th element of “Y” represent the number of accidents of i-th id in the j-th year, and (i,j,2)-th element of “Y” represents the salary of i-th id in the j-th year, and (i,j,3)-th element of “Y” represent sports car (0 or 1) of i-th id in the j-th year. (Please type everything element to define “Y")

<font color='green'> Explanation starts here</font>

(ID, Year, info)의 배열이 되도록 Y를 만든다.

<font color='green'> Explanation ends here</font>

<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
import numpy as np

Y = np.array([[[0,157,1],[1,167,1],[0,130,1],[1,145,1],[2,170,1]],
              [[1,250,0],[3,260,0],[2,263,0],[1,273,0],[0,290,0]],
              [[0,301,0],[0,120,0],[0,30,0],[1,100,0],[3,502,0]]])
Y

array([[[  0, 157,   1],
        [  1, 167,   1],
        [  0, 130,   1],
        [  1, 145,   1],
        [  2, 170,   1]],

       [[  1, 250,   0],
        [  3, 260,   0],
        [  2, 263,   0],
        [  1, 273,   0],
        [  0, 290,   0]],

       [[  0, 301,   0],
        [  0, 120,   0],
        [  0,  30,   0],
        [  1, 100,   0],
        [  3, 502,   0]]])

c> Solve part b> again by utilizing “N”, “Salary”, and “Sports” defined in a>.

<font color='green'> Explanation starts here</font>

np.stack을 이용해서 N, Salary, Sports를 합쳐야한다. N, Salary, Sports는 (3,5)의 2차원이기 떄문에 np.stack을 사용하여 한 차원 증가시켜줘야 한다. 또한 열을 기준으로 합쳐지도록 axis = 2로 해야한다.

<font color='green'> Explanation ends here</font>


<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
import numpy as np

np.stack((N, Salary, Sports), axis = 2)

array([[[  0, 157,   1],
        [  1, 167,   1],
        [  0, 130,   1],
        [  1, 145,   1],
        [  2, 170,   1]],

       [[  1, 250,   0],
        [  3, 260,   0],
        [  2, 263,   0],
        [  1, 273,   0],
        [  0, 290,   0]],

       [[  0, 301,   0],
        [  0, 120,   0],
        [  0,  30,   0],
        [  1, 100,   0],
        [  3, 502,   0]]])

d> Create an array “Y2” of shape [3,3,5] where (i,1,j)-th element of“Y” represent the number of accidents of i-th id in the j-th year, and (i,2,j)-th element of“Y”represents the salary of i-th id in the j-th year, and (i,3,j)-th element of“Y”represent sports car (0 or 1) of i-th id in the j-th year. (Please type everything element to define“Y2)

<font color='green'> Explanation starts here</font>

(ID, info, Year)의 배열이 되도록 Y2를 만든다.

<font color='green'> Explanation ends here</font>

<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
Y2 = np.array([[[0,1,0,1,2],[157,167,130,145,170],[1,1,1,1,1]],
               [[1,3,2,1,0],[250,260,263,273,290],[0,0,0,0,0]],
               [[0,0,0,1,3],[301,120,30,100,502],[0,0,0,0,0]]])
Y2

array([[[  0,   1,   0,   1,   2],
        [157, 167, 130, 145, 170],
        [  1,   1,   1,   1,   1]],

       [[  1,   3,   2,   1,   0],
        [250, 260, 263, 273, 290],
        [  0,   0,   0,   0,   0]],

       [[  0,   0,   0,   1,   3],
        [301, 120,  30, 100, 502],
        [  0,   0,   0,   0,   0]]])

e> Solve part d> again by converting an array “Y” into “Y2”

<font color='green'> Explanation starts here</font>

Y를 axis = 1을 기준으로 concatenate 한 후, 역행렬을 구한다. (9,5)의 2차원 행렬로 되어있으므로, (3,3,5)의 3차원 행렬로 reshape해준다.

<font color='green'> Explanation ends here</font>

<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
Y = np.array([[[0,157,1],[1,167,1],[0,130,1],[1,145,1],[2,170,1]],
              [[1,250,0],[3,260,0],[2,263,0],[1,273,0],[0,290,0]],
              [[0,301,0],[0,120,0],[0,30,0],[1,100,0],[3,502,0]]])

np.concatenate(Y, axis = 1).T.reshape(3,3,5)

array([[[  0,   1,   0,   1,   2],
        [157, 167, 130, 145, 170],
        [  1,   1,   1,   1,   1]],

       [[  1,   3,   2,   1,   0],
        [250, 260, 263, 273, 290],
        [  0,   0,   0,   0,   0]],

       [[  0,   0,   0,   1,   3],
        [301, 120,  30, 100, 502],
        [  0,   0,   0,   0,   0]]])

f> Solve part d> again by utilizing “N”, “Salary”, and “Sports” defined in a>.

<font color='green'> Explanation starts here</font>

np.stack을 이용해서 N, Salary, Sports를 합쳐야한다. N, Salary, Sports는 (3,5)의 2차원이기 떄문에 np.stack을 사용하여 한 차원 증가시켜줘야 한다. 또한 행을 기준으로 합쳐지도록 axis = 1로 해야한다.

<font color='green'> Explanation ends here</font>

<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
import numpy as np

np.stack((N, Salary, Sports), axis = 1)

array([[[  0,   1,   0,   1,   2],
        [157, 167, 130, 145, 170],
        [  1,   1,   1,   1,   1]],

       [[  1,   3,   2,   1,   0],
        [250, 260, 263, 273, 290],
        [  0,   0,   0,   0,   0]],

       [[  0,   0,   0,   1,   3],
        [301, 120,  30, 100, 502],
        [  0,   0,   0,   0,   0]]])

## Problem 8
（Sequential search） In computer science, a linear search or sequential
search is a method for finding an element within a list. It sequentially checks each
element of the list until a match is found or the whole list has been searched.
Write a Python function which do sequential search and return all the locations of
target in the given list, and return –1 if there is no match

<font color='green'> Explanation starts here</font>

lst라는 인덱스를 저장할 빈 리스트를 만든 후, input list길이만큼 for문을 돌려 input list값과 target 값이 같으면 lst에 해당 인덱스 값을 추가하는 코드를 작성해야 한다. 또한 일치하는 값이 없어 lst가 빈 리스트로 남아있을 경우, -1을 return 한다. 

<font color='green'> Explanation ends here</font>


<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
def sq_search(input_list, target):
    lst = []
    for i in range(len(input_list)):
        if input_list[i] == target:
            lst.append(i)
    if lst == []:
        return -1
    return lst 
    
input_list = np.array([1,5,3,4,1,3,1])
target = np.array([3])
sq_search(input_list, target)

[2, 5]

## Problem 9
 (Selection sort) In class, we study the following selection sort algorithm.

 ```
 def finding_minidx(alist):
    n = len(alist)
    minidx = 0
    for i in range(1,n):
        if alist[minidx] > alist[i]:
            minidx=i return minidx

def selection_sort(alist):
    n = len(alist)
    subarray = []
    while alist:
        current_minidx_in_alist = finding_minidx(alist)
        current_min_in_alist = alist.pop(current_minidx_in_alist)
        subarray.append(current_min_in_alist)
    return subarray
# Test code:
myinput=[3,5,1,2]
selection_sort(myinput)
print(myinput)

 ```
 However, in the code above, memory for subarray is somehow wasted.
Here, we provide more efficient version in terms of memory using the following code. (Smaller numbers are moved to left deck while the bigger number are on
the right deck.) 

```
def selection_sort_efficient(alist):
    n=len(alist)
    for i in range(n-1):
        idx = finding_minidx(alist[i:]) ####
        if alist[i] > alist[idx]:
            alist[i], alist[idx] = alist[idx], alist[i]
# Test code:
myinput=[3,5,1,2]
selection_sort_efficient(myinput)
print(myinput)
```
However, it seems that the function “selection_sort_efficient” seems to be not
working well. Modify the function “selection_sort_efficient” so that it works well.

<font color='green'> Explanation starts here</font>

```
for i in range(n-1):
    idx = finding_minidx(alist[i:]) + i
```
위와 같이 고쳐야 함. finding_minidx(alist[i:])의 결과 나온 인덱스 값은 원래 alist의 인덱스 값보다 i만큼 작기 때문에 i를 더해줘야 alist의 해당 인덱스 값과 일치함.
   
<font color='green'> Explanation ends here</font>


<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
def finding_minidx(alist):
    n = len(alist)
    minidx = 0
    for i in range(1,n):
        if alist[minidx] > alist[i]:
            minidx=i 
    return minidx

def selection_sort_efficient(alist):
    n=len(alist)
    for i in range(n-1):
        idx = finding_minidx(alist[i:]) + i ####
        if alist[i] > alist[idx]:
            alist[i], alist[idx] = alist[idx], alist[i]
# Test code:
myinput=[3,5,1,2]
selection_sort_efficient(myinput)
print(myinput)

[1, 2, 3, 5]

## Problem 10
(Insertion sort) You are given the following code to do insertion sort. Complete the code by writing proper codes for (*)~(****), and run the code to check whether it is working well input “a = [3,4,1,2,7,5]”.

```
def ins_sort(inp_list):
    n=len(inp_list)
    for i in range(n):
        key=inp_list[i]
        j=i-1
        while (j >=0) & (key < inp_list[j]):
            inp_list[j+1] = (*)
            j = (**)
        inp_list[ (***) ] = (****)
```
<font color='green'> Explanation starts here</font>

(j >=0) & (key < inp_list[j])인 경우, inp_list[j+1]에 inp_list[j]을 넣어줌으로써 큰 값을 오른쪽으로 이동시킨다. 또한 j = j - 1으로 j값을 하나씩 작아지게 만들어 while문을 반복하게 한다. while문을 빠져나오면 마지막으로 inp_list[j+1]에 key값을 삽입하여 정렬한다. 이러한 식으로 for문을 반복하면 작은 값은 왼쪽으로, 큰 값은 오른쪽으로 정렬된다.

<font color='green'> Explanation ends here</font>


<font color='red'><<<**Finally Answer**>>></font>

In [ ]:
def ins_sort(inp_list):
    n=len(inp_list)
    for i in range(n):
        key=inp_list[i]
        j=i-1
        while (j >=0) & (key < inp_list[j]):
            inp_list[j+1] = inp_list[j]
            j = j - 1
        inp_list[j+1] = key

a = [3,4,1,2,7,5]
ins_sort(a)
a

[1, 2, 3, 4, 5, 7]